CREATE DATABASE [SoftUni]
GO

USE [SoftUni]
GO

CREATE TABLE [Towns]
(
[Id] INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(70) NOT NULL
)

CREATE TABLE [Addresses]
(
[Id] INT PRIMARY KEY IDENTITY, 
[AddressText] VARCHAR(100) NOT NULL, 
[TownId] INT NOT NULL FOREIGN KEY REFERENCES [Towns]([Id]), 
)

CREATE TABLE [Departments]
(
[Id] INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(70) NOT NULL
)

CREATE TABLE [Employees]
(
[Id] INT PRIMARY KEY IDENTITY,
[FirstName] VARCHAR(50) NOT NULL, 
[MiddleName] VARCHAR(50) NOT NULL, 
[LastName] VARCHAR(50) NOT NULL,
[JobTitle] VARCHAR(50) NOT NULL, 
[DepartmentId] INT NOT NULL FOREIGN KEY REFERENCES [Departments]([Id]), 
[HireDate] DATETIME2 NOT NULL, 
[Salary] SMALLINT NOT NULL, 
[AddressId] INT NOT NULL FOREIGN KEY REFERENCES [Addresses]([Id])
)